FROM mysql:8

# Environment variables to initialize the database and user
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=app_user
ENV MYSQL_PASSWORD=1234
ENV MYSQL_ROOT_PASSWORD=root1234

# Expose MySQL port
EXPOSE 3306

# Volume for persistent data
VOLUME /var/lib/mysql